<!-- begin vendor/pledg/module-pledg-payment-gateway/view/frontend/templates/widget/block.phtml -->

<script type="text/javascript">

    require(['jquery', 'pledgWidget'], function($, pledgWidget) {

        switchMerchant = (element) => {
            pledgWidget.switchMerchant(element);
        };

        initiateWidget = () => {
            pledgWidget.initiateWidget();
        };

        showPopup = (element) => {
            pledgWidget.showPopup(element);
        };

    });

</script>

<?php
    $blockOptions = $block->getOptions();
?>

<div
    id="pledg-primary-widget"
    class="pledg-widget-nav"
>
    <ul>
        <?php
            $captionSpanText = '';
            foreach ($blockOptions['merchants'] as $key => $merchant) { 
                $activation = '';
                $merchantIconClass = 'merchantIcon' . $key;
                if ($blockOptions['activeMerchant'] == $merchantIconClass) {
                    $activation = ' active';
                    $captionSpanText = $merchant['caption'];
                }
        ?>
            <li
                class="merchantIcon <?php echo $merchantIconClass; ?><?php echo $activation; ?>"
                data-code="<?php echo htmlspecialchars($merchant['code'], ENT_QUOTES, 'UTF-8'); ?>"
                data-caption="<?php echo htmlspecialchars($merchant['caption'], ENT_QUOTES, 'UTF-8'); ?>"
                data-schedule="<?php echo htmlspecialchars($merchant['schedule'], ENT_QUOTES, 'UTF-8'); ?>"
                data-type="<?php echo $merchant['type']; ?>"
                data-fees="<?php echo $merchant['fees']; ?>"
                data-currency="<?php echo $merchant['options']['currency']; ?>"
                data-currency-sign="<?php echo $merchant['options']['currencySign']; ?>"
                data-key="<?php echo $key; ?>"
                onclick="switchMerchant(this)"
                onKeyPress="javascript:void(0)"
            >
                <?php echo $merchant['icon']; ?>
            </li>
        <?php
            }
        ?>
    </ul>
    <div id="pledg-primary-line" class="pledg-line"></div>
</div>

<div id="pledg-widget-caption">
    <span><?php echo $captionSpanText; ?></span>
    <i class="pledg-modal-link fa-solid fa-circle-exclamation" onclick="showPopup(this)" onKeyPress="javascript:void(0)"></i>
</div>

<!-- end vendor/pledg/module-pledg-payment-gateway/view/frontend/templates/widget/block.phtml -->
