<!-- begin vendor/pledg/module-pledg-payment-gateway/view/frontend/templates/widget/container.phtml -->

<?php
    $blockOptions = $block->getOptions();

    if ($blockOptions['widgetActivation'] === '1') {
?>

    <div id="pledg-popup-overlay">
    </div>

    <div
        id="pledg-widget"
        class="pledg-widget-<?php echo $blockOptions['widgetType']; ?>"
        data-options="<?php echo htmlspecialchars($blockOptions['options'], ENT_QUOTES, 'UTF-8'); ?>"
        data-captions="<?php echo htmlspecialchars($blockOptions['captions'], ENT_QUOTES, 'UTF-8'); ?>"
    >
        <?php
            include ($block->getTemplateFile('Pledg_PledgPaymentGateway::widget/block.phtml'));
        ?>

    </div>

    <div id="pledg-overlay-content">

        <?php
            include ($block->getTemplateFile('Pledg_PledgPaymentGateway::widget/popup.phtml'));
        ?>

    </div>

    <script type="text/javascript">

        require(['jquery', 'pledgWidget'], function($, pledgWidget) {

            /*
            * The 'DOMContentLoaded' event tells us when we can init the widget
            * with data. It is triggered only when the page is loaded.
            */
            (function ($) {

                $(document).ready(() => {
                    pledgWidget.initiateOverlay();
                    pledgWidget.initiateWidget();

                    // Select the node that will be observed for mutations
                    const arrElements = $('#cart-totals');
                    if (arrElements.length > 0) {
                        const targetNode = arrElements[0];

                        // Options for the observer (which mutations to observe)
                        const config = { attributes: false, childList: true, subtree: true };

                        // Callback function to execute when mutations are observed
                        const callback = (mutationList, observer) => {
                            const urlWidgetUpdateController = '<?php echo $blockOptions['urlWidgetUpdateController']; ?>';
                            for (const mutation of mutationList) {
                                if (mutation.type === "childList") {
                                    if (
                                        mutation.target.matches('.table-wrapper')
                                        && !(mutation.target.matches('.table-wrapper._block-content-loading'))
                                    ) {
                                        let widgetType = '<?php echo $blockOptions['widgetType']; ?>';
                                        pledgWidget.onCartUpdate(urlWidgetUpdateController, widgetType);
                                    }
                                }
                            }
                        };

                        const observer = new MutationObserver(callback);
                        observer.observe(targetNode, config);
                    }

                });

            }(jQuery));

        });

    </script>

<?php
    }
?>

<!-- end vendor/pledg/module-pledg-payment-gateway/view/frontend/templates/widget/container.phtml -->
