<?php
/**
 * @var \Pledg\PledgPaymentGateway\Block\Info $block
 */
$specificInfo = $block->getAdminSpecificInformation();
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value):?>
            <tr>
                <th><?= $block->escapeHtml($label) ?>:</th>
                <td>
                    <?php if ($label === __('View in PledgBySofinco dashboard')->getText()) { ?>
                        <?= $value ?>
                    <?php } else { ?>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    <?php } ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
